# Generated by Django 4.0.1 on 2022-03-28 02:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='National_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A RhD positive'), ('A-', 'A RhD negative'), ('B+', 'B RhD positive'), ('B', 'B RhD negative'), ('O+', 'O RhD positive'), ('O-', 'O RhD negative'), ('AB+', 'AB RhD positive'), ('AB-', 'AB RhD negative')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position_class',
            field=models.CharField(max_length=200, verbose_name='Responsibility'),
        ),
    ]
