# Generated by Django 4.0.1 on 2022-03-28 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_national_id_teacher_gender_teacher_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='present_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
