# Generated by Django 4.0.1 on 2022-03-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary_grade',
            field=models.CharField(blank=True, choices=[('Teacher Grade', 'Teacher Grade')], max_length=20, null=True),
        ),
    ]
