# Generated by Django 4.0.1 on 2022-03-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_salary_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20, null=True),
        ),
    ]
