# Generated by Django 4.0.1 on 2022-03-07 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Staff',
        ),
    ]
